#!/bin/bash
help () {
echo "Supernode Settings:"
echo "status | off | on | auto"
}

status () {
	supernode_status=$(/bin/cat /etc/supernode-status/supernode.status)
	supernode_mode=$(/bin/cat /etc/supernode-status/supernode.mode)
	loadbalancing=$(cat /etc/supernode-status/loadbalancing.mode)

	echo "Supernode Status: (Ist-Zustand)"
	if [ $supernode_status == 0 ]; then
		echo "Supernode ist Offline"
	elif [ $supernode_status == 1 ]; then
		echo "Supernode läuft (Loadbalancing)"
	elif [ $supernode_status == 2 ]; then
		echo "Supernode läuft (Dauer-Ein)"
	elif [ $supernode_status == 3 ]; then
		echo "Supernode Offline (Loadbalancing)"
	fi
	if [ $loadbalancing = 1 ]; then
		echo "Loadbalancing ist Aktiv"
	else
		echo "Loadbalancing ist Deativiert"
	fi
}

off () {
	echo 0 > /etc/supernode-status/supernode.mode
	echo 0 > /etc/supernode-status/loadbalancing.mode
	
	echo "Supernode Aus"
}

on () {
	echo 1 > /etc/supernode-status/supernode.mode
	echo 0 > /etc/supernode-status/loadbalancing.mode
	echo "Supernode Dauer-An"
}

auto () {
	echo 1 > /etc/supernode-status/loadbalancing.mode
	echo 1 > /etc/supernode-status/supernode.mode
	echo "Supernode Aktiviert inkl. Loadbalance"
}
$1
