#!/bin/bash
help () {
echo "Supernode Settings:"
echo "status | off | on | auto"
}

status () {
	supernode_status=$(/bin/cat /etc/supernode-status/supernode.status)
	supernode_mode=$(/bin/cat /etc/supernode-status/supernode.mode)
	loadbalancing=$(cat /etc/supernode-status/loadbalancing.mode)

	echo "Supernode Status: (Ist-Zustand)"
	if [ $supernode_status == 0 ]; then
		echo "Supernode ist Offline"
	elif [ $supernode_status == 1 ]; then
		echo "Supernode läuft"
	elif [ $supernode_status == 2 ]; then
		echo "Supernode läuft (Backup)"
	fi
	for service in bird bird6 dhcpd radvd python named
    do
    	if [ "$(/bin/cat /etc/supernode-status/$service.status)" = "1" ]; then
    		echo -e "$service \e[1;4;93mläuft\e[0m"
    	else
    		echo -e "$service \e[1;4;91mläuft nicht\e[0m"
    	fi
    done
}

off () {
	echo 0 > /etc/supernode-status/supernode.mode
	echo "Supernode Aus"
}

on () {
	echo 1 > /etc/supernode-status/supernode.mode
	echo "Supernode An"
}

backup () {
	echo 2 > /etc/supernode-status/supernode.mode
	echo "Supernode Aktiviert inkl. Backup"
}
$1
